version: '3'

services:
  rasa-nlu:
    image: rasa_nlu_avx2:latest
    volumes:
      - ${PWD}/backend/config_nlu_template.yml:/app/config_nlu_template.yml
      - ${PWD}/backend/none_intent_classifier.py:/app/none_intent_classifier.py
      - ${PWD}/backend/data/nlu:/app/data/nlu
      - ${PWD}/backend/models/nlu-prod:/app/models/nlu
      - ${PWD}/backend/logs/rasa_nlu:/app/logs
    command: python -m rasa_nlu.train -c config_nlu.yml -d data/nlu -o models/nlu --fixed_model_name ${NLU_MODEL} --project ${NLU_PROJECT}
